manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: badjeff
      url-base: https://github.com/badjeff
    
    - name: Senkoi
      url-base: https://github.com/Senkoi

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    
    - name: zmk-feature-move-determin
      remote: Senkoi
      revision: main

  self:
    path: config